config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :comments
  end
  
  root "posts#index"

  get "/about", to: "pages#about"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:body, :name))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		
		if @post.save
			redirect_to @post
		else
			render 'new'
		end

	end

	def show
	end

	def edit
	end

	def update
		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		
		redirect_to root_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :body)
	end
	def find_post
		@post = Post.find(params[:id])
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_title">Posted <%= time_ago_in_words(comment.created_at) %> ago</p>
	</div>
	<% if user_signed_in? %>
		<p><%= link_to "Delete", [comment.post, comment], method: :delete, class: "button", data: { confirm: "Are you sure?" } %></p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %> <br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :body %> <br>
		<%= f.text_area	:body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tumbl esque | Post with style</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
<aside id="sidebar">
	<nav>
		<ul>
			<li class="category"><%= link_to "Tumbl esque", root_path %></li>
			<li><%= link_to "Posts", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>
		<% if !user_signed_in? %>
		<p class="sign_in"><%= link_to "User Login", new_user_session_path %></p>
		<% end %>
	</nav>
</aside>

<section id="main_content">
	<header id="header">
		<% if current_page?(root_path) %>
			<p>Post Feed</p>
		<% elsif current_page?(about_path) %>
			<p>About My Site</p>
		<% else %>
			<p><%= link_to "Back to Post Feed", root_path %></p>
		<% end %>
		

	<% if user_signed_in? %>
			<div class="buttons">
				<button class="button"><%= link_to "Make Post", new_post_path %></button>
				<button class="button"><%= link_to "Log Out", destroy_user_session_path , method: :delete %></button>
			</div>
	<% end %>
	</header>

	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert") %> 
	<% end %>

	<%= yield %>

</section>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag 'profile.jpeg' %>
	</div>
	<div id="content">
		<h1>It's Mister Stick Figure</h1>
		<p>Viennese percolator, beans, grinder fair trade pumpkin spice variety dark, french press steamed sugar bar coffee robusta. Doppio roast decaffeinated, milk as black cortado, siphon flavour, cortado milk aftertaste espresso turkish caffeine aged pumpkin spice saucer americano arabica. Breve white turkish id, flavour, fair trade, extraction whipped white id macchiato shop sugar extraction, chicory carajillo con panna ut saucer. Cinnamon, dark irish cappuccino aromatic robust, redeye arabica a strong sweet, aged barista, caramelization breve to go french press est crema.</p>
<p>Redeye americano foam affogato beans plunger pot breve, coffee arabica cortado mug dripper aged. Arabica mug, redeye, extra frappuccino turkish roast, espresso, affogato sit that, extra espresso americano ristretto sweet. Extra rich, white arabica cup skinny americano, turkish macchiato wings barista coffee half and half latte est body aftertaste. Trifecta, acerbic spoon java aged seasonal, id french press, espresso viennese roast, galão cream chicory skinny espresso.</p>
<p>Affogato, instant id, aromatic white saucer as latte mazagran, so, carajillo café au lait, half and half acerbic caramelization galão mazagran. Caffeine mocha strong galão, lungo dark et blue mountain, as, ut beans irish percolator, java half and half mazagran irish cup decaffeinated. Java, fair trade qui beans, chicory steamed seasonal, dripper barista latte robust aftertaste mocha. Froth body white whipped affogato, doppio café au lait robust siphon foam eu cream extra.</p>
<p>Extra, steamed cup whipped cultivar to go, turkish id black coffee so extra aftertaste café au lait siphon doppio. Turkish white mazagran cappuccino ristretto, beans aromatic espresso, robust fair trade macchiato cup aftertaste extraction spoon galão skinny galão. Id roast id redeye crema, cream seasonal est percolator sweet espresso crema seasonal macchiato. Siphon crema, dark, sugar, mazagran half and half, mazagran carajillo pumpkin spice crema aftertaste cinnamon cup aged plunger pot.</p>
<p>Irish bar, robust, galão, cappuccino, ut irish, espresso frappuccino id latte sugar ristretto arabica shop viennese, medium, cultivar spoon grinder foam robusta. Barista a robust rich milk robusta, french press caffeine blue mountain as trifecta acerbic a galão id whipped plunger pot, et americano sit that cup ristretto. Id cultivar coffee rich, pumpkin spice doppio that, coffee, aged sweet beans instant, breve robusta robust so frappuccino. Half and half, id, robust, sweet, aftertaste, roast, sweet cappuccino, instant body, decaffeinated milk cinnamon eu organic trifecta.</p>
<p>Qui, cultivar iced variety aromatic black spoon dripper mocha variety, café au lait, crema brewed strong crema cup aroma chicory. Foam aftertaste et aged fair trade latte milk, instant spoon affogato viennese grounds a, doppio aroma robust skinny beans black, trifecta cream aromatic qui half and half. Blue mountain so roast filter and, wings, seasonal, extraction a, body qui caramelization latte cup, blue mountain, decaffeinated viennese single origin variety robusta aftertaste. Grounds latte dark brewed roast galão cream id wings, a siphon, aroma as fair trade, wings, ut french press chicory seasonal spoon breve crema extraction coffee.</p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>


	<p><%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p><%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
		<h1>Fix the post</h1>
		
		<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="body"><%= truncate(post.body, length:160) %></p>
		<p class="date"><%= time_ago_in_words(post.created_at) %> ago</p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
		<h1>Make Something</h1>
	
		<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title"><%= @post.title %></h1>
	
	<p class="date">Submitted <%= time_ago_in_words(@post.created_at) %> ago
		<% if user_signed_in? %>
			| <%= link_to "Make Changes", edit_post_path(@post) %> | <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: 'Really? This cannot be undone.... don\'t come crying to me.... Are you really certain?'} %>
		<% end %>
		</p>
	
	<p class="body"><%= simple_format(@post.body) %></p>

	<div id="comments">
		<h2><%= pluralize(@post.comments.count, "Comment") %></h2>
		<%= render @post.comments %>
		<h3>Join the discussion:</h3>
		<%= render "comments/form" %>
	</div>
</div>